version: '3.8'
services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # environment variables از Dokploy تزریق می‌شوند 
    # اگر با dokploy تزریق نشد باید مقدار زیر را اضافه کرد برای پروژه فایل 
    #  env_file:
    #  - .env
    restart: unless-stopped